###Introduction to Big Data
- HW:3
- TEAM: 6
- Memebers: 22000245 Moon Byeori
        

# < Question 1 – All Movies data >

( 1-1, 5 pts ) Import “movies_dataset_from_allmovie.json” to a pandas dataframe typed variable
called movie_df and show the first 5 rows.

In [ ]:
from google.colab import drive #Mount Google Drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd #pandas moduls import
import json #json moduls import

movie_df = pd.read_json('/content/drive/MyDrive/IntBigData/movies_dataset_from_allmovie.json') #Read in the json file via the correct path and store it in the movie_df variable
movie_df.head(5) #Output the top 5 rows

<ipython-input-4-b740d4c0e8d5>:4: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  movie_df = pd.read_json('/content/drive/MyDrive/IntBigData/movies_dataset_from_allmovie.json') #정확한 경로를 통해 json파일을 읽어들이고 movie_df변수에 저장
<ipython-input-4-b740d4c0e8d5>:4: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  movie_df = pd.read_json('/content/drive/MyDrive/IntBigData/movies_dataset_from_allmovie.json') #정확한 경로를 통해 json파일을 읽어들이고 movie_df변수에 저장
<ipython-input-4-b740d4c0e8d5>:4: FutureWarning: The b

name                  genre  \
0  10 Days, 10 Years: Nicaraguan Elections of 1990  Culture &amp; Society   
1   1-2-3 Magic: Effective Discipline for Children              Education   
2                        10 Keys to Personal Power               Business   
3           10,000 Maniacs: Time Capsule 1982-1990                  Music   
4                              10 Rillington Place           Crime, Drama   

  released_at                                             poster language  \
0  1990-01-01                                                               
1  1990-01-01                                                     English   
2         NaT                                                               
3  1990-01-01  https://cps-static.rovicorp.com/1/avg/cov310/d...  English   
4  1971-02-10  https://cps-static.rovicorp.com/2/Open/Sony%20...  English   

            director                     domain duration  \
0                     https://www.allmovie.com/    0H54M   
1                     https://www.allmovie.com/     2H0M   
2                     https://www.allmovie.com/     1H4M   
3                     https://www.allmovie.com/    0H58M   
4  Richard Fleischer  https://www.allmovie.com/    1H51M   

                                            synopsis  \
0                                                      
1  Presented by clinical psychiatrist Thomas Phel...   
2                                                      
3  With their thoughtful folk rock sound and lyri...   
4  10 Rillington Place is the true story of Briti...   

                                             trailer average_rating  \
0                                                                     
1                                                                     
2                                                                     
3                                                                     
4  https://video.internetvideoarchive.net/video.m...            8.1   

                                                cast          crawled_at  \
0                                                    2021-05-02 20:30:28   
1                                                    2021-05-02 20:30:29   
2                                                    2021-05-02 20:30:29   
3                                                    2021-05-02 20:30:29   
4  10 Rillington Place, Richard Attenborough, Jud... 2021-05-02 20:30:29   

                                                 url  \
0  https://www.allmovie.com/movie/10-days-10-year...   
1  https://www.allmovie.com/movie/1-2-3-magic-eff...   
2  https://www.allmovie.com/movie/10-keys-to-pers...   
3  https://www.allmovie.com/movie/10000-maniacs-t...   
4  https://www.allmovie.com/movie/10-rillington-p...   

                                    _id  
0  72706835-65b7-5559-9d16-73c43b2667bd  
1  81e8678a-1cf5-58d7-ae5e-1b6ae80d0835  
2  0d09f252-ca38-5e85-8d5f-a91a3f32dc4c  
3  5b8e0dbb-3b48-5600-a544-651f9020245d  
4  2b5d82ef-2429-52fb-b5ab-ffbd7ede3c3b

( 1-2, 5 pts ) Describe the data dimension of movie_df. (Hint: .shape)

In [ ]:
movie_df.shape #Output the number of rows and columns in movie_df

(10524, 15)

( 1-3, 5 pts) What are the names of columns used in movie_df?

In [ ]:
names = movie_df.columns #Print the column names of movie_df
print(names)

Index(['name', 'genre', 'released_at', 'poster', 'language', 'director',
       'domain', 'duration', 'synopsis', 'trailer', 'average_rating', 'cast',
       'crawled_at', 'url', '_id'],
      dtype='object')


( 1-4, 5 pts) How many unique movie genres are included in movie_df?


In [ ]:
genre = movie_df.genre.unique() # Storing a single count of genres in movie_df as a list,
len(genre) #Counting the number of list elements

590

( 1-5, 10 pts) What are the list of movies released in year 2004? To answer this question, we have to
use datetime64 variable called “released_at”. Write down Python codes that filters samples released in
year 2004. ( Hint: Use .dt.strftime() ).

In [ ]:
movie_df.released_at # I just checked the released_at variable and it's hard to determine the exact date

0       1990-01-01
1       1990-01-01
2              NaT
3       1990-01-01
4       1971-02-10
           ...    
10519   1936-01-01
10520   1937-01-01
10521   1988-01-01
10522   1991-01-01
10523   1959-01-01
Name: released_at, Length: 10524, dtype: datetime64[ns]

In [ ]:
movie_df['released_at'] = pd.to_datetime(movie_df['released_at']) # Changed the type of the released_at variable to the data type
movies_2004 = movie_df[movie_df['released_at'].dt.strftime('%Y') == '2004'] #From the release_at variable, strftime outputs an entry with the year 2004 in the strftime.
print(movies_2004['name'])

2810                             Beyond the Next Mountain
2912                                      The Big Red One
3002    Billy Graham Classic Message: The Road to Arma...
7071                                 D-Day: Plus 40 Years
9099                          Salute to Jelly Roll Morton
Name: name, dtype: object


( 1-6, 10 pts) Which genres take the greatest proportion in movie_df and its proportion? To figure this
out, write down Python codes that generate results below. Do you think this result is sufficient? If you
think not, suggest an alternative solution.


In [ ]:

genres = movie_df.genre #After checking the list element, we have a genre for each work, so we need to calculate the percentage for each.
genres_count = pd.Series(genres).value_counts() # Count each element in an array
ratio = genres_count/genres_count.sum()
print(ratio.head(5))
print(ratio.tail(5))


genre
Drama                      0.094166
Music                      0.082003
Comedy                     0.062429
Sports &amp; Recreation    0.047605
History                    0.043995
Name: count, dtype: float64
genre
Romance, Sports &amp; Recreation                    0.000095
History, Travel                                     0.000095
Culture &amp; Society, Language &amp; Literature    0.000095
Crime, Comedy                                       0.000095
Action, Adult, Adventure, Drama, Western            0.000095
Name: count, dtype: float64


In [ ]:
genre = movie_df.genre.unique() # Storing a single count of genres in movie_df as a list,
genre #After checking the list element, we have a genre for each work, so we need to calculate the percentage for each.
genre1 = movie_df.genre
genres = [genre1.strip() for sublist in genre1 for genre1 in sublist.split(',') if genre1.strip()] # Separates elements in each array based on , for genre
genre_counts = pd.Series(genres).value_counts() # Count each element in an array
genre_ratios = genre_counts / genre_counts.sum()# Calculated the percentage of each array element = genre by dividing each element by the total number
print(genre_ratios.head(5))
print(genre_ratios.tail(5))

Drama                0.125018
Comedy               0.075713
Music                0.075081
Action               0.072763
Children's/Family    0.054994
Name: count, dtype: float64
Education                              0.002669
Business                               0.002318
Family &amp; Personal Relationships    0.002318
Epic                                   0.002248
News [TV]                              0.000070
Name: count, dtype: float64


( 1-7, 10 pts) What is the name of director who has made the most films? To answer this question,
write down Python codes that generates results below.

In [ ]:
director1 = movie_df.director.value_counts().head(5) #count director columns value and print 5 heads
director2 = movie_df.director.value_counts().tail(5)#count director columns value and print 5 tails
combined_directors = pd.concat([director1, director2])# merge 2 values
print(combined_directors)


director
                       4551
Sam Newfield             20
Michael Curtiz           16
William Berke            12
Richard Fleischer        12
George Bowers             1
Gerry Lively              1
Marcelo Epstein           1
J.G. Patterson, Jr.       1
Bill D'Elia               1
Name: count, dtype: int64


( 1-8, 10 pts) It seems Sam Newfield is the director who made 20 films. Write down Python codes that
generates data.frame that presents the frequency of Sam Newfield’s movie genre as shown below.

In [ ]:
dirSam = movie_df[movie_df['director'] == 'Sam Newfield']# Find and return sam newfield in supervision items
genres_count = dirSam['genre'].value_counts()# Count and store the number of genres in the returned dataframes
genres_count.columns = ['Genre', 'Count'] #Create a dataframe with genre and count values to output
print(genres_count)

genre
Action, Western                            8
Western                                    5
Adventure, Drama                           1
Action, Adventure, Western                 1
Action, Adventure, Mystery                 1
Action, Mystery, Western                   1
Drama, Horror                              1
Action, Spy Film, Western                  1
Action, Crime, Drama, Spy Film, Western    1
Name: count, dtype: int64


( 1-9, 10 pts) When running a data analysis, not all columns are used, but only the important or highly
relevant ones are used. Use movie_df to create a new variable called movie_df_new, which does not
include column 'trailer','url','poster', and ‘crawled_at’. Use .drop() method.


In [ ]:
movie_df_new = movie_df.drop(['trailer', 'url', 'poster', 'crawled_at'], axis=1) #Removed variables that are not needed for the new data frame
movie_df_new

name  \
0      10 Days, 10 Years: Nicaraguan Elections of 1990   
1       1-2-3 Magic: Effective Discipline for Children   
2                            10 Keys to Personal Power   
3               10,000 Maniacs: Time Capsule 1982-1990   
4                                  10 Rillington Place   
...                                                ...   
10519                                 Feud of the West   
10520                                Feud of the Trail   
10521                                            Fever   
10522                                            Fever   
10523                         La fièvre monte à El Pao   

                            genre released_at language           director  \
0           Culture &amp; Society  1990-01-01                               
1                       Education  1990-01-01  English                      
2                        Business         NaT                               
3                           Music  1990-01-01  English                      
4                    Crime, Drama  1971-02-10  English  Richard Fleischer   
...                           ...         ...      ...                ...   
10519  Action, Adventure, Western  1936-01-01  English       Harry Fraser   
10520             Action, Western  1937-01-01  English        Robert Hill   
10521                     Mystery  1988-01-01  English       Craig Lahiff   
10522                    Thriller  1991-01-01  English      Larry Elikann   
10523                       Drama  1959-01-01  English        Luis Buñuel   

                          domain duration  \
0      https://www.allmovie.com/    0H54M   
1      https://www.allmovie.com/     2H0M   
2      https://www.allmovie.com/     1H4M   
3      https://www.allmovie.com/    0H58M   
4      https://www.allmovie.com/    1H51M   
...                          ...      ...   
10519  https://www.allmovie.com/     1H2M   
10520  https://www.allmovie.com/    0H58M   
10521  https://www.allmovie.com/    1H32M   
10522  https://www.allmovie.com/    1H36M   
10523  https://www.allmovie.com/    1H49M   

                                                synopsis average_rating  \
0                                                                         
1      Presented by clinical psychiatrist Thomas Phel...                  
2                                                                         
3      With their thoughtful folk rock sound and lyri...                  
4      10 Rillington Place is the true story of Briti...            8.1   
...                                                  ...            ...   
10519  Neither the best nor worst of Hoot Gibson's we...                  
10520  Produced back-to-back with Mystery Range (1937...                  
10521  Here's the &quot;dramatis personae&quot; of Th...                  
10522  In this violent made-for cable actioner, a pai...                  
10523  A moral decay leading to revolution is paralle...            6.8   

                                                    cast  \
0                                                          
1                                                          
2                                                          
3                                                          
4      10 Rillington Place, Richard Attenborough, Jud...   
...                                                  ...   
10519  Joan Barclay, Feud of the West, Walter Futter,...   
10520  Harlene Wood, Harley Wood, Vane Calvert, Myste...   
10521     Bill Hunter, Gary Sweet, Mary Regan, The Fever   
10522                                                      
10523  Miguel Angle Ferriz, Maria Felix, Gerard Phill...   

                                        _id  
0      72706835-65b7-5559-9d16-73c43b2667bd  
1      81e8678a-1cf5-58d7-ae5e-1b6ae80d0835  
2      0d09f252-ca38-5e85-8d5f-a91a3f32dc4c  
3      5b8e0dbb-3b48-5600-a544-651f9020245d  
4      2b5d82ef-2429-52fb-b5ab-ffbd

( 1-10, 10 pts) Using movie_df_new, create a new variable called movie_df_new_rename with the
changed names as shown below.


In [ ]:
movie_df_new.columns #View the current variable and start changing it

movie_df_new = movie_df_new.rename(columns={ #Renaming variables via rename
    'name': 'MovieTitle',
    'genre': 'Genre',
     'released_at': 'ReleaseDate',
     'language': 'Language'
})
movie_df_new['Year'] = movie_df_new['ReleaseDate'].dt.strftime('%Y') #We also created and added a new variable for the year
movie_df_new.columns #Outputting the final copy

Index(['MovieTitle', 'Genre', 'ReleaseDate', 'Language', 'director', 'domain',
       'duration', 'synopsis', 'average_rating', 'cast', '_id', 'Year'],
      dtype='object')

# < Question 2 – Numpy Array >

( 2-1, 2.5 pts ) Generate numpy matrix as shown below.

In [ ]:
import numpy as np #numpy module import


In [ ]:
arr = np.arange(1,10,2) #Specify a new array, only odd numbers from 1 to 10
arr

array([1, 3, 5, 7, 9])

( 2-2, 2.5 pts ) Generate numpy matrix as shown below.

In [ ]:
arr = np.arange(1, 12, 2).reshape(2, 3) #Create an odd array of 1 to 12 in arr, then adjust it to fit into a two-dimensional array of three
arr

array([[ 1,  3,  5],
       [ 7,  9, 11]])

( 2-3, 2.5 pts ) Generate numpy matrix as shown below.

In [ ]:
arr = np.arange(1,16,2).reshape(4,2) #Create an array of odd numbers from 1 to 16 in arr, then adjust it to fit into a four-dimensional array by two
arr

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

( 2-4, 2.5 pts ) Generate numpy matrix as shown below.

In [ ]:
arr = np.arange(1,10).reshape(3,3)#Create an array from 1 to 9 in arr, then adjust it to fit into a three-dimensional array of three
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

( 2-5, 10 pts, 2.5 pts each ) Given numpy matrix, mynumpy, answer the following questions: 1) summation of 0D, 2) average of 1D, 3) maximum value, and 4) standard deviation. (Hint: Adjust the axis parameter for questions 2-5-1 and 2-5-2)

In [ ]:
arr = np.arange(5,91,5).reshape(6,3) #First, create an array matrix
arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60],
       [65, 70, 75],
       [80, 85, 90]])

In [ ]:
# questioin1
sum_0d = np.sum(arr) # Adds up the total value of the array metrics you created
print(sum_0d)

855


In [ ]:
#question2
avg_1d = np.mean(arr, axis=1) #Find the average for each column of an array metric
print(avg_1d)

[10. 25. 40. 55. 70. 85.]


In [ ]:
#question3
max_value = np.max(arr) #Returns the largest value in an array metric
print(max_value)

90


In [ ]:
#question4
std_dev = np.std(arr) #Get the std value, standard deviation of an array metric
print(std_dev)

25.940637360455632
